# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: 
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "testrail"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "backup-tools"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "ios-insights"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "android-l10n-integrity"
    schedule: 
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "android-performance"
    schedule: 
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "telemetry-expiry"
    schedule:
      interval: "weekly"
