name: Digest ios test results and import to BigQuery

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow'
        required: true
        default: 'main'

jobs:
  process-test-results:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configurae Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: moz-mobile-tools
          # service_account_key: ${{ secrets.GCP_SA_IOS_TESTS_INSIGHTS }}
          # export_default_credentials: true
      - name: Authenticate with Google Cloud
        run: |
          echo '${{ secrets.GCP_SA_IOS_TESTS_INSIGHTS }}' > gcloud-key.json
          gcloud auth activate-service-account --key-file=gcloud-key.json
          rm -f gcloud-key.json

      - name: List all the HTML files in the bucket
        id: list-html
        run: |
          echo "List HTML file on gs://test_insights/build/report/"
          gsutil ls gs://mobile-reports/public/test_ios_insights/build/reports/*.html > html_files.txt
          cat html_files.txt
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.13'
        
      - name: Install dependencies
        run: pip install -r ios-insights/requirements.txt

      - name: Convert HTML a NDJSON
        run: |
          set -x  # Enables command logging for debugging
          mkdir -p processed
          while IFS= read -r file_html; do
            echo "Processing $file_html"
            # Download the HTML file
            gsutil cp "$file_html" .
            name_base=$(basename "$file_html" .html)

            # Print available files for debugging
            echo "Files in the current directory:"
            ls -lh

            # Execute the conversion script
            echo "Running conversion script..."
            python ios-insights/convertHTML2NDJSON.py "$name_base.html" > "$name_base.json"
            
            # Check if JSON was generated
            if [ -f "$name_base.json" ]; then
                echo "JSON generated successfully: $name_base.json"
                mv "$name_base.json" processed/
            else
                echo "ERROR: JSON file was not created!"
            exit 1
            fi
            
            # Save the generated JSON in the processed folder
            # mv "$name_base.json" processed/
            done < html_files.txt
        shell: /usr/bin/bash -e

      - name: Upload generated NDJSON to the bucket
        run: |
          for ndjson_file in processed/*.ndjson; do
            echo "Uplod $ndjson_file to bucket..."
            gsutil cp "$ndjson_file" gs://mobile-reports/public/test_ios_insights/build/reports/
          done
