name: Digest ios test results and import to BigQuery

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow'
        required: true
        default: 'main'

jobs:
  process-test-results:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configurae Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: moz-mobile-tools
          # service_account_key: ${{ secrets.GCP_SA_IOS_TESTS_INSIGHTS }}
          # export_default_credentials: true
      - name: Authenticate with Google Cloud
        run: |
          echo '${{ secrets.GCP_SA_IOS_TESTS_INSIGHTS }}' > gcloud-key.json
          gcloud auth activate-service-account --key-file=gcloud-key.json
          rm -f gcloud-key.json

      - name: List all the HTML files in the bucket
        id: list-html
        run: |
          echo "List HTML file on gs://test_insights/build/report/"
          gsutil ls gs://mobile-reports/public/test_ios_insights/build/reports/*.html > html_files.txt
          cat html_files.txt
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.13'
        
      - name: Install dependencies
        run: pip install -r ios-insights/requirements.txt

      - name: Convert HTML a NDJSON
        shell: bash
        run: |
          set -x  # Enables command logging for debugging
          mkdir -p processed
          while IFS= read -r file_html; do
            echo "Processing $file_html"
            gsutil cp "$file_html" .
            name_base=$(basename "$file_html" .html)

            echo "Checking if $name_base.html exists..."
            ls -lh
            if [ ! -f "$name_base.html" ]; then
                echo "ERROR: $name_base.html not found!"
                exit 1
            fi

            # Check if the Python script exists
            if [ ! -f "ios-insights/convertHTML2NDJSON.py" ]; then
                echo "ERROR: convertHTML2NDJSON.py not found!"
                ls -lh ios-insights
                exit 1
            fi

            echo "Running conversion script..."
            python ios-insights/convertHTML2NDJSON.py "$name_base.html" "$name_base.ndjson"

            if [ -s error_log.txt ]; then
                echo "Python script error output:"
                cat error_log.txt
            fi

            if [ -f "$name_base.ndjson" ]; then
                echo "NDJSON successfully created: $name_base.ndjson"
                mv "$name_base.ndjson" processed/
            else
                echo "ERROR: NDJSON file not generated!"
                exit 1
            fi
          done < html_files.txt
            
      - name: Upload generated NDJSON to the bucket
        run: |
          for ndjson_file in processed/*.ndjson; do
            echo "Uplod $ndjson_file to bucket..."
            gsutil cp "$ndjson_file" gs://mobile-reports/public/test_ios_insights/build/reports/
          done

      - name: Import NDJSON to BigQuery
        run: |
          for file in processed/*.ndjson; do
            echo "Importing $file into BigQuery..."
            bq --location=US load \
               --source_format=NEWLINE_DELIMITED_JSON \
               --time_partitioning_field=timestamp \
               --clustering_fields=test_suite,test_case \
               ${{ secrets.GCP_SA_IOS_TESTS_INSIGHTS_TABLE }} \
               "$file" \
               ios-insights/schema.json
          done
        
      - name: Clear bucket
        if: ${{ success() }}
        run: |
           echo "Delete HTML and JSON files from the bucket..."
           gsutil rm gs://test_insights/build/report/*.html
           gsutil rm gs://test_insights/build/report/*.ndjson